apiVersion: v1
kind: Service
metadata:
  name: tech-quiz
  namespace: tech-quiz
  labels:
    app: tech-quiz
spec:
  type: NodePort
  selector:
    app: tech-quiz
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
